### ISSUE TITLE
加入 antd 组件，打包后启动服务端加载报错  @root-entry-name: default;

### ISSUE THREAD

**Issue by elza2** [baiyuze/koa-react-ssr-render#3]
1. 引入 antd 组件 
    `"antd": "^4.24.7",`

2. 在 page / index.jsx 页面加入一个 Button 组件
   `<Button type="primary">点我加2</Button>`

3. 启动服务端
   `node index.js`

5. 访问 localhost:3000， 报错

报错行 `const dom = require(path.join(process.cwd(),`app/build/${fileName}.js`)).default;`

```
/Users/xxx/src/koa-react-ssr-render/node_modules/antd/lib/style/default.less:2
@root-entry-name: default;
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1040:15)
    at Module._compile (node:internal/modules/cjs/loader:1076:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/xxx/src/koa-react-ssr-render/node_modules/antd/lib/button/style/index.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/xxx/src/koa-react-ssr-render/app/build/page1.js:1:2171)
```

**Comment by pardSun** [comment]
姿势不对
